version: "3"

name: daytrader-microservices

services:
  daytrader-web-service:
    image: daytrader-web-service
    hostname: daytrader-web-service
    container_name: daytrader-web-service
    ports:
      - 5443:5443
    networks:
      - daytrader

  daytrader-gateway-service:
    image: daytrader-gateway-service
    hostname: daytrader-gateway-service
    container_name: daytrader-gateway-service
    ports:
      - 2443:2443
    networks:
      - daytrader

  daytrader-portfolios-service:
    image: daytrader-portfolios-service
    hostname: daytrader-portfolios-service
    container_name: daytrader-portfolios-service
    ports:
      - 3443:3443
    networks:
      - daytrader
#
  daytrader-quotes-service:
    image: daytrader-quotes-service
    hostname: daytrader-quotes-service
    container_name: daytrader-quotes-service
    ports:
      - 4443:4443
    networks:
      - daytrader

  daytrader-accounts-service:
    image: daytrader-accounts-service
    hostname: daytrader-accounts-service
    container_name: daytrader-accounts-service
    ports:
      - 1443:1443
    networks:
      - daytrader

networks:
  daytrader: null